### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by tigerclawn82** [trivago/gollum#1]
I want to use [Sourcegraph](https://sourcegraph.com) for gollum code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/trivago/gollum. (It should only take 30 seconds.)

Thank you!

**Comment by arnecls** [comment]
Here you go :)

**Comment by tigerclawn82** [comment]
Thank you so much :)
