### ISSUE TITLE
Un-pin version of github.com/aws/aws-sdk-go in glide and update the library 

### ISSUE THREAD

**Issue by ppar** [trivago/gollum#106]
The version of `github.com/aws/aws-sdk-go` is pinned in `./glide.yaml` to the repo's commit ID because the sources we have under `./vendor/github.com/aws/aws-sdk-go` do not match the library's intended version (1.8.2). 

We should set the version to something meaningful, do a glide update, and then verify that the plugin(s?) using that library still work.

Commit 40681065ad2416c9560953393cda4751ce54d388

**Comment by ppar** [comment]
Affected modules:
```
$ grep -Eir github.com/aws/aws-sdk-go *.go $(find . -type d -mindepth 1 -maxdepth 1 -not -name vendor -not -name .git)
./consumer/kinesis.go:	"github.com/aws/aws-sdk-go/aws"
./consumer/kinesis.go:	"github.com/aws/aws-sdk-go/aws/awserr"
./consumer/kinesis.go:	"github.com/aws/aws-sdk-go/aws/credentials"
./consumer/kinesis.go:	"github.com/aws/aws-sdk-go/aws/session"
./consumer/kinesis.go:	"github.com/aws/aws-sdk-go/service/kinesis"
./producer/firehose.go:	"github.com/aws/aws-sdk-go/aws"
./producer/firehose.go:	"github.com/aws/aws-sdk-go/aws/credentials"
./producer/firehose.go:	"github.com/aws/aws-sdk-go/aws/session"
./producer/firehose.go:	"github.com/aws/aws-sdk-go/service/firehose"
./producer/kinesis.go:	"github.com/aws/aws-sdk-go/aws"
./producer/kinesis.go:	"github.com/aws/aws-sdk-go/aws/credentials"
./producer/kinesis.go:	"github.com/aws/aws-sdk-go/aws/session"
./producer/kinesis.go:	"github.com/aws/aws-sdk-go/service/kinesis"
./producer/s3.go:	"github.com/aws/aws-sdk-go/aws"
./producer/s3.go:	"github.com/aws/aws-sdk-go/aws/credentials"
./producer/s3.go:	"github.com/aws/aws-sdk-go/aws/session"
./producer/s3.go:	"github.com/aws/aws-sdk-go/service/s3"
```

**Comment by arnecls** [comment]
If you want to see the current state, have a look at the gilde.lock.
Glide.yaml only represents the "intent", see: https://glide.readthedocs.io/en/latest/versions/ .
If you stick to [semver](http://semver.org) it is perfectly ok to define it like that.
It just says >=1.8.2 and < 2.0.0, i.e. patches + extensions but no breaking changes.
I'm fine with that.
