### ISSUE TITLE
Kinesis Producer StreamMapping incorrectly documented?

### ISSUE THREAD

**Issue by jbrook** [trivago/gollum#12]
The examples and documentation for the Kinesis producer seem to be slightly wrong. I think it should be 'StreamMapping' and not 'StreamMap'.

**Comment by arnecls** [comment]
Thanks for pointing this out :+1:
I'll update the docs asap.

**Comment by arnecls** [comment]
Docs for 0.4.3dev have been updated.

**Comment by arnecls** [comment]
0.4.3 released -> fixed
