### ISSUE TITLE
Reduce file polling in consumer.File

### ISSUE THREAD

**Issue by arnecls** [trivago/gollum#137]
In regard to PR #134 and #135 we need to reduce the file polling done by consumer.File.
Either we should more intelligently do the polling or try to utilise fsevents, see https://github.com/fsnotify/fsnotify.

**Comment by arnecls** [comment]
The merge does not implement what is stated above.
As stated in the PRs for 0.4.0 this a symptomatic fix, not addressing the real issue.

**Comment by msiebeneicher** [comment]
How discussed: We implement a "file system event watcher" as separated mode and keep the current `poll mode` as default.

I would not recommend to use the file system event mode for log rotations or heavy frequented file.
