### ISSUE TITLE
cookbook/wiki

### ISSUE THREAD

**Issue by predmond** [trivago/gollum#14]
I wiki/cookbook of common patterns would be really helpful.

**Comment by arnecls** [comment]
That was the original idea behind the [configs folder](https://github.com/trivago/gollum/tree/master/config). Sadly I did not have the time to update those a lot lately. Currently you can have a look at the original [blog post](http://tech.trivago.com/2015/06/22/gollum/)  or the [examples from the documentation](http://gollum.readthedocs.io/en/latest/examples/config.html).

Do you have a specific use case you need help with?

**Comment by predmond** [comment]
I have some go code that I might be able to replace with Gollum.

1. A json object is produced on a kafka topic. It looks something like:
```
{
  "key" : "a uuid"
  "payload" : "a big string"
  ... some other fields
}
```
2. A consumer takes the json and writes it to redis using key as the key and payload as the value.
3. The payload field is dropped and the json is produced/forwarded to another kafka topic.

For 2. it is possible to extract the payload using gollum but I don't think I can easily use the key field as the redis key. For 3. I don't see a way to do this with the existing json formatters.

**Comment by arnecls** [comment]
The problem is that the redis producer currently does not support a separate key formatter.
That feature is not much of a problem to add (the kafka producer for example already supports this) and I think it's a good idea to support that.
I'll add that feature to the 0.4.4 branch.

**Comment by predmond** [comment]
Ah. I didn't see thhe kafka KeyFormatter. That looks perfect. What about deleting fields from JSON? Is there a way to do that too?

**Comment by arnecls** [comment]
format.ProcessJSON should do that, but apparently the remove case is missing. I'll put that on the list.
You could do also that with format.JSON but that's way too much work and not very easy to do right.

**Comment by arnecls** [comment]
Pushed the changes to the 0.4.4 branch.
I tested format.ProcessJSON, but I still need to create a redis test case.
You can either wait until tomorrow or be brave and try the changes directly :)

**Comment by arnecls** [comment]
I enabled the wiki and added a "cookbook" section.
The wiki is open for everyone, so if you have a cool usecase feel free to add it.
We will gradually move the examples from the config folder over to this section.
