### ISSUE TITLE
Testconfig mode (-tc / -testconfig) doesn't work

### ISSUE THREAD

**Issue by ppar** [trivago/gollum#154]
Gollum has a mode to "test" a configuration file (for what? syntax errors or also plugin startup?), but all of the invocations below just produce the "usage" message and exit. 

./gollum -tc -c config/http_auth_receive.conf
./gollum -testconfig config/http_auth_receive.conf
./gollum -ll 3 -tc -c config/http_auth_receive.conf

./gollum -tc config/http_auth_receive.conf
./gollum -testconfig -c config/http_auth_receive.conf
./gollum -ll 3 -tc config/http_auth_receive.conf

**Comment by arnecls** [comment]
The "tc" should do two things
a) check if the yaml is parsable (which it does)
b) check if all plugins can be instantiated correctly without really activiating them (which it does not)

So this should be about properly implementing b)

**Comment by ppar** [comment]
c) Print an unambigious result instead of the usage instructions
