### ISSUE TITLE
kafka consumer should support consumer groups

### ISSUE THREAD

**Issue by predmond** [trivago/gollum#17]
Sarama cluster has support for consumer groups: https://github.com/bsm/sarama-cluster

Note sarama-cluster requires kafka >= 0.9.

**Comment by arnecls** [comment]
As of 0.4.4 we included Sarama 1.10 so we finally have support for Kafka 0.10.
I think this will be added once we switch our cluster to 0.10, but if anyone wants to add this to the 0.4.5 branch I would be very grateful, too, as I am currently working on finishing the 0.5.0 changes.

**Comment by arnecls** [comment]
@predmond Is this ok for you?

**Comment by arnecls** [comment]
And a big thanks to @relud by the way.
