### ISSUE TITLE
Feature request: Metrics in Prometheus format

### ISSUE THREAD

**Issue by dkleuser** [trivago/gollum#221]
## Issue description

It would be great if Gollums metrics were also exposed in the format that Prometheus expects.

## Context

This would enable us to monitor Gollum with [Prometheus](https://prometheus.io/).

## Possible Solution

There is an official Golang client library for exposing metrics in the required format: https://github.com/prometheus/client_golang
As it is the default that Prometheus expects, it would be nice if the metrics were available at the endpoint `/prometheus`.

Please also see https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels for the allowed characters for metric labels.

**Comment by arnecls** [comment]
Another solution would be to switch to [go-metrics](https://github.com/rcrowley/go-metrics/blob/master/README.md) and use their prometheus adapter: https://github.com/deathowl/go-metrics-prometheus 

However - we should benchmark go-metrics first as metrics already cause quite an overhead in gollum.
Also we must somewhat stay backwards compatible as there are tools around processing gollum metrics ... and we already somewhat broke this with 0.5
