### ISSUE TITLE
Mention the gollum wiki project to avoid confusion

### ISSUE THREAD

**Issue by mralusw** [trivago/gollum#260]
Amazingly, this repo manages to have the same name and about the same current version (0.5.x) as the well-known gollum wiki (https://github.com/gollum/gollum), yet, of course, completely unrelated purposes.

Perhaps mention that this is not the... other project... somewhere... to avoid confusion.

**Comment by arnecls** [comment]
Good catch.
I was vaguely aware that another project named gollum exists.
I added a link to the readme in this commit https://github.com/trivago/gollum/commit/479cafe8533a1b06256067ef2ad03f11c0a1e8e4
