### ISSUE TITLE
ENTRYPOINT in Dockerfile is wrong.

### ISSUE THREAD

**Issue by breadmj** [trivago/gollum#41]
running `docker run -it --rm trivago/gollum`
results in `docker: Error response from daemon: oci runtime error: exec: "/go/src/gollum/gollum": stat /go/src/gollum/gollum: no such file or directory.`

**current**
ENTRYPOINT ["/go/src/gollum/gollum"]

**should be**
ENTRYPOINT ["/go/src/github.com/trivago/gollum/gollum"]

or how about '*go install*' after '*go build*'?

**Comment by arnecls** [comment]
The dockerfile is quite old, looks like it needs an update.
Thanks for pointing this out.

**Comment by Exeu** [comment]
here is the fix #42

**Comment by arnecls** [comment]
Thanks a lot!
