### ISSUE TITLE
response error using socket producer.

### ISSUE THREAD

**Issue by breadmj** [trivago/gollum#51]
There might be a bug in the socket producer code.

**error log snippet**

> ERROR: socket.go:171: Socket response error: read tcp 172.17.0.2:57002->**_my-mac-ip_**:5880: i/o timeout

**Observations**
- gollum says that error log every time after flushing(producing) packets into the socket.
- But, on the receiving side (which is listening to 5880 port in this case), packets arrive intact. There is no losing packet as far as I observed.

**Envirionment**
- macOS Sierra , CoreOS 1010.5 (occurs on linux and osx both)
- Docker engine 1.12.1
- gollum v0.4.4

If you need additional info, let me know.
Thanks.

**Comment by breadmj** [comment]
sorry, it was my misuse of **_Acknowledge_** parameter.
I gotta close this issue.

**Comment by breadmj** [comment]
But how about bring documents(https://github.com/trivago/gollum/tree/master/docs) to the front?

I thoght that at first there was no documentation of gollum in here cause I couldn't find it in README.

**Comment by arnecls** [comment]
There already are two links at the very top, but I agree that we should add a separate section, too, as not everyone is familiar with these buttons.
![docs](https://cloud.githubusercontent.com/assets/6131989/19069591/d0448c74-8a27-11e6-873d-fe8f6661b854.png)

**Comment by arnecls** [comment]
Added a documentation section to the readme

**Comment by breadmj** [comment]
Thanks!
