### ISSUE TITLE
Cloudwatch logs plugin

### ISSUE THREAD

**Issue by luqasz** [trivago/gollum#55]
Hi.

I am writing a daemon for sending logs to AWS cloudwatch logs service. My friend showed me your project and I am interested in contributing my [code](https://github.com/ClearcodeHQ/Go-Forward) as a plugin. My question is, under which license my contribution needs to be ?

**Comment by arnecls** [comment]
Hi - sorry for the (very) late reply.
Gollum is using the apache 2.0 license (see LICENSE file) so everything directly included is definitely under that license, too. External libraries (vendor folder) are currently running under the license they provided.

**Comment by luqasz** [comment]
Ok. So basicly if I do a PR, it must be licensed under apache 2.0

**Comment by arnecls** [comment]
Yes, as it is not possible to switch Licenses for single files (as far as I know).
If you have a concrete problem I can also ask our legal department to clarify, as I only have limited knowledge about this topic.

**Comment by luqasz** [comment]
That is ok. I want to stabilize my project then I will make a PR. Thx for info.
