### ISSUE TITLE
config validation issues

### ISSUE THREAD

**Issue by glaslos** [trivago/gollum#62]
Hi, I intended to extend the HTTP consumer with basic auth. Unfortunately I am struggling in figuring out where to register new config values I added to the consumer. Code can be found here: https://github.com/glaslos/gollum/commit/bfacc98f93e13968debea892426f2c1390857f75 
I'd appreciate some feedback.

**Comment by glaslos** [comment]
Any chance to get some help with this issue?

**Comment by arnecls** [comment]
As I'm back from vacation since yesterday - yes :)
The code you posted looks fine so far.
Config values you query inside a config method are automatically "registered". No additional work needed. Are you missing something specific?

**Comment by glaslos** [comment]
Ah, my bad, I was getting the following error messages and confused them with a config verification that was failing:
```
Warning: pluginconfig.go:60: Unknown configuration key in consumer.Http: Htpasswd
Warning: pluginconfig.go:60: Unknown configuration key in consumer.Http: BasicRealm
```
What actually happened was that I didn't change the import path of the consumer package to my fork, so my changes never made it into the build. Changing the import path fixed the problem. Sending a pull request now to get some feedback and opinion if this a feature you guys want to see in your repo. Thanks for making me question myself :)
