### ISSUE TITLE
Write a homebrew formular to install gollum on mac

### ISSUE THREAD

**Issue by andygrunwald** [trivago/gollum#7]
See [Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook) and [Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#acceptable-formulae).

How this can look like you can get this from the [What I Talk About When I Talk About CLI Tool By Golang #gocon](https://speakerdeck.com/tcnksm/what-i-talk-about-when-i-talk-about-cli-tool-by-golang-number-gocon) presentation.

**Comment by andreis** [comment]
Here's a start: https://github.com/Homebrew/homebrew/pull/42751

**Comment by andygrunwald** [comment]
:beer: THX

**Comment by arnecls** [comment]
Cool - just saw this popping up during a homebrew update. :+1: 
Now we need only to update it to 0.4.0 ^_^

**Comment by dunn** [comment]
:information_desk_person: https://github.com/Homebrew/homebrew/commit/db52ca5d350f2ccd27a9fcc2b4064490c16968b2

**Comment by arnecls** [comment]
:tada: thx a lot
