### ISSUE TITLE
Evaluate logrus as a replacement for tgo/tlog

### ISSUE THREAD

**Issue by arnecls** [trivago/gollum#89]
Evaluate if https://github.com/sirupsen/logrus can be a sufficient replacement for tlog.
We could benefit from several features brought by this package + external developers most likely already know it.

- log scopes must be possible
- logrus must connect to the gollum pipeline
- logs before startup and after shutdown must be handled correctly

**Comment by glaslos** [comment]
I would also consider zap: https://github.com/uber-go/zap

**Comment by ppar** [comment]
The log level should also be selecatble in gollum's configuration, instead of the command line like it is now. This way you could e.g. write error and debug logs to different destinations and/or with different rotation regimes.

**Comment by ppar** [comment]
Evaluation (actually, mostly complete implementation) branch at https://github.com/trivago/gollum/tree/enhancement/89-logrus

In general Logrus looks like a good fit. 

- Log scopes are available as ad-hoc "metadata" fields
- Using the logrus.Hook interface, we can
  1. write to the _GOLLUM_ stream as before
  2. insert the log level and those ad-hoc fields as metadata in the Gollum message
  3. filter and route the _GOLLUM_ stream in Gollum's config per e.g. log scope or level (not fully tested yet)
- Handling the startup/shutdown scenarios should be doable simply by setting logrus's output target to `os.Stdout` or `ioutil.Discard` as appropriate (not fully tested yet, also timeouts / log entry spooling - TBD)
